tag = "darkshuffle-node_systems"
writes = [
    "darkshuffle-Game",
    "darkshuffle-Draft",
    "darkshuffle-Entropy",
    "darkshuffle-DraftCard",
    "darkshuffle-Node",
    "darkshuffle-MonsterNode",
    "darkshuffle-PotionNode",
    "darkshuffle-CardNode",
    "darkshuffle-Battle",
    "darkshuffle-BattleEffects",
    "darkshuffle-HandCard",
]