kind = "DojoModel"
class_hash = "0x382e0ab00fd97b97eeaf781760b999521f8d006e84f3de61304075d159599db"
original_class_hash = "0x382e0ab00fd97b97eeaf781760b999521f8d006e84f3de61304075d159599db"
abi = "manifests/dev/abis/base/models/darkshuffle_models_game_game.json"
name = "darkshuffle::models::game::game"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = false

[[members]]
name = "active"
type = "bool"
key = false

[[members]]
name = "in_draft"
type = "bool"
key = false

[[members]]
name = "in_battle"
type = "bool"
key = false

[[members]]
name = "battles_won"
type = "u16"
key = false
