kind = "DojoModel"
class_hash = "0x63e9b04641c04422c4427de51b573dc5fb41a8b44c7d663eecb8cd8dcedbc23"
original_class_hash = "0x63e9b04641c04422c4427de51b573dc5fb41a8b44c7d663eecb8cd8dcedbc23"
abi = "manifests/dev/abis/base/models/darkshuffle_models_battle_battle.json"
name = "darkshuffle::models::battle::battle"

[[members]]
name = "battle_id"
type = "usize"
key = true

[[members]]
name = "game_id"
type = "usize"
key = false

[[members]]
name = "round"
type = "u16"
key = false

[[members]]
name = "deck_iteration"
type = "u16"
key = false

[[members]]
name = "card_index"
type = "u16"
key = false

[[members]]
name = "hero_health"
type = "u16"
key = false

[[members]]
name = "hero_energy"
type = "u16"
key = false

[[members]]
name = "monster_id"
type = "u16"
key = false

[[members]]
name = "monster_attack"
type = "u16"
key = false

[[members]]
name = "monster_health"
type = "u16"
key = false
