kind = "DojoModel"
class_hash = "0x3599a98729f675a95afa0c189cb91bbebbf3473f7e4a72b0c65504f90877c8a"
original_class_hash = "0x3599a98729f675a95afa0c189cb91bbebbf3473f7e4a72b0c65504f90877c8a"
abi = "manifests/dev/abis/base/models/darkshuffle_models_draft_draft.json"
name = "darkshuffle::models::draft::draft"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "card_count"
type = "u8"
key = false
