kind = "DojoModel"
class_hash = "0x4f22b79433e782b75b2045fae29fd456d88a1c07bde68eb115e0024c1d87159"
original_class_hash = "0x4f22b79433e782b75b2045fae29fd456d88a1c07bde68eb115e0024c1d87159"
abi = "manifests/dev/abis/base/models/darkshuffle_models_battle_round_effects.json"
name = "darkshuffle::models::battle::round_effects"

[[members]]
name = "battle_id"
type = "usize"
key = true

[[members]]
name = "creatures_played"
type = "u16"
key = false
