kind = "DojoModel"
class_hash = "0x2803a30da12cf97a6ef1109c2e11ad6302f1446a2d41775585a80ce896afc28"
original_class_hash = "0x2803a30da12cf97a6ef1109c2e11ad6302f1446a2d41775585a80ce896afc28"
abi = "manifests/dev/abis/base/models/darkshuffle_models_draft_draft_option.json"
name = "darkshuffle::models::draft::draft_option"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "option_id"
type = "u8"
key = true

[[members]]
name = "card_id"
type = "u16"
key = false
