kind = "DojoModel"
class_hash = "0x9a2cd4e30bd5d842e1d650d1716f37c6f5df9d39980d96fd881f0ed46ccde8"
original_class_hash = "0x9a2cd4e30bd5d842e1d650d1716f37c6f5df9d39980d96fd881f0ed46ccde8"
abi = "manifests/dev/abis/base/models/darkshuffle_models_battle_hand_card.json"
name = "darkshuffle::models::battle::hand_card"

[[members]]
name = "battle_id"
type = "usize"
key = true

[[members]]
name = "hand_card_number"
type = "u8"
key = true

[[members]]
name = "card_id"
type = "u16"
key = false
