[world]
seed = ""
name = "Dark Shuffle"

[namespace]
default = "darkshuffle"

[writers]
"darkshuffle" = [
    "darkshuffle-game_systems",
    "darkshuffle-battle_systems",
    "darkshuffle-season_systems",
    "darkshuffle-draft_systems",
    "darkshuffle-map_systems",
]

[env]
world_address = "0x06a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f"
world_block = 948010
