[world]
seed = "darkshuffle5"
name = "Dark Shuffle"
description = "Enter the darkness"
website = "https://darkshuffle.io/"

[world.socials]
x = "https://x.com/await_0x"
github = "https://github.com/Await-0x/dark-shuffle"

[namespace]
default = "darkshuffle"

[writers]
"darkshuffle" = [
    "darkshuffle-game_systems",
    "darkshuffle-battle_systems",
    "darkshuffle-season_systems",
    "darkshuffle-draft_systems",
    "darkshuffle-map_systems",
    "darkshuffle-config_systems",
]

[env]
world_address = "0x0581f5394a8d43cebd38eda3d8e4e4f9bfb566c04485ba28cb47393bb0a82fe4"