[world]
seed = ""
name = "Dark Shuffle"

[namespace]
default = "darkshuffle_s0"

[writers]
"darkshuffle_s0" = [
    "darkshuffle_s0-game_systems",
    "darkshuffle_s0-battle_systems",
    "darkshuffle_s0-season_systems",
    "darkshuffle_s0-draft_systems",
    "darkshuffle_s0-map_systems",
    "darkshuffle_s0-config_systems",
]

[env]
world_address = "0x06a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f"
world_block = 948010
