[world]
seed = "darkshuffle3"
name = "Dark Shuffle"
description = "Enter the darkness"
website = "https://darkshuffle.io/"

[world.socials]
x = "https://x.com/await_0x"
github = "https://github.com/Await-0x/dark-shuffle"

[namespace]
default = "darkshuffle"

[writers]
"darkshuffle" = [
    "darkshuffle-game_systems",
    "darkshuffle-battle_systems",
    "darkshuffle-season_systems",
    "darkshuffle-draft_systems",
    "darkshuffle-map_systems",
    "darkshuffle-config_systems",
]

[env]
world_address = "0x0700e53e56662d99e411252e22f6960feaae7fd5c14c2f68f518e26ba0bbcc5d"