[world]
seed = "darkshuffle2"
name = "Dark Shuffle"
description = "Enter the darkness"
website = "https://darkshuffle.io/"

[world.socials]
x = "https://x.com/await_0x"
github = "https://github.com/Await-0x/dark-shuffle"

[namespace]
default = "darkshuffle"

[writers]
"darkshuffle" = [
    "darkshuffle-game_systems",
    "darkshuffle-battle_systems",
    "darkshuffle-season_systems",
    "darkshuffle-draft_systems",
    "darkshuffle-map_systems",
]

[env]
# world_address = "0x03f51728fe54e47fd9b61400c0821254df7401e3a04d99d14919704653c460b8"