[world]
seed = ""
name = "Dark Shuffle"

[namespace]
default = "darkshuffle_s0"

[writers]
"darkshuffle_s0" = [
    "darkshuffle_s0-game_systems",
    "darkshuffle_s0-battle_systems",
    "darkshuffle_s0-season_systems",
    "darkshuffle_s0-draft_systems",
    "darkshuffle_s0-map_systems",
    "darkshuffle_s0-config_systems",
]

[env]
world_address = "0x044c4ffdf401b1fe8c4b75eb8c8076d28dd91940ea31de93814dc82e1410b86e"
world_block = 1014817
