[package]
cairo-version = "=2.7.0"
name = "darkshuffle"
version = "0.4.2"

[cairo]
sierra-replace-ids = true

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.15.1" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.15.1" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.15.1" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.17" }

[[target.dojo]]

[tool.fmt]
sort-module-level-items = true

[profile.sepolia]
[profile.slot]
[profile.mainnet]