[package]
name = "darkshuffle"
version = "0.3.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.4" }

[profile.prod.tool.dojo.world.namespace]
default = "darkshuffle"

[tool.dojo.world.namespace]
default = "darkshuffle"

[tool.dojo.env]
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address = "0x68bd46f4b09cc876e0ac692e1943351eb63b1d95e9406b4c0bff833a9edb0eb"

[profile.prod.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/darkshuffle/katana"
account_address = "0x6af2ac345307fe6c7b71fbc0b612571082ca402af4ed6a18f9786de1e1f1efd"
private_key = "0x58e48aa7e04ef9b1323b7402ad0c73dee9137741d8c7f915d558ccd5d00d045"
world_address = "0x68bd46f4b09cc876e0ac692e1943351eb63b1d95e9406b4c0bff833a9edb0eb"

[[target.dojo]]

[tool.dojo.world]
seed = "darkshuffle"
name = "Dark Shuffle"
description = "Enter the darkness"
website = "https://darkshuffle.dev/"

[profile.prod.tool.dojo.world]
seed = "darkshuffle"
name = "Dark Shuffle"
description = "Enter the darkness"
website = "https://darkshuffle.dev/"

[tool.fmt]
sort-module-level-items = true