[package]
name = "darkshuffle"
version = "0.2.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.3" }

[tool.dojo.world.namespace]
default = "darkshuffle"

[tool.dojo.env]
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
# world_address = "0x02579a62f7c4a0f63e556370fad4d110ba8a63eeae6014cfb6ba2a739b14820f"

[profile.prod.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/darkshuffle/katana"
account_address = "0x1ac9ffb92ef2b848b6b9feb8a06b9c3311077007e9075517fe629165f8c111"
private_key = "0x4aa974632b58a8946752d559f2b061b8fc9949c2006c8ca2429e27a2584341c"
world_address = "0x7bb7ebdd7e71f60cdc9d411b5069442931990aa4ead38c117f38d77d9cedbfd"

[[target.dojo]]

[tool.dojo.world]
seed = "darkshuffle"
name = "Dark Shuffle"
description = "Enter the darkness"
website = "https://darkshuffle.dev/"

[tool.fmt]
sort-module-level-items = true