[package]
cairo-version = "2.5.0"
name = "darkshuffle"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

[profile.prod.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/darkshuffle/katana"
account_address = "0x7df39d39e72fb6534bce8176b4be470c7ad34b7126e7f5fe02b9c7d37aa5d20"
private_key = "0x157fff457b7e678cced53b7fccdd86030a8598541902ec672b9cb8dcd17db6"

[[target.dojo]]

[lib]

[tool.dojo.world]
name = "The Cave"
description = "Enter the darkness"
website = "https:/darkshuffle.monster/"

[tool.fmt]
sort-module-level-items = true